---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: Pod
metadata:
  name: landingpage
  labels:
    app: landingpage
  namespace: production
spec:
  containers:
    - name: landingpage
      image: gcr.io/qubeship/landingpage:latest

----
apiVersion: v1
kind: ReplicationController
metadata:
  name: landingpage-controller
  labels:
    app: landingpage
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: landingpage
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        app: landingpage
    spec:
      containers:
      - name: landingpage
        image: gcr.io/qubeship/landingpage:latest
        ports:
        - containerPort: 443
        resources:
          limits:
            cpu: 100m
