
----
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: landingpage-deployment
  labels:
    app: landingpage
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: landingpage
      namespace: production
    spec:
      containers:
      - name: landingpage
        image: %gcr.io/image:version%
        ports:
        - containerPort: 443
        resources:
          limits:
            cpu: 100m
