---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: landingpage
  name: landingpage-service
  namespace: production
spec:
  ports:
  - port: 443
  selector:
    app: landingpage
  type: LoadBalancer